env:
  local:
    server:
      port: 8080
    database:
      name: hybird
      host: localhost
      port: 5432
      user: postgres
      password: root

  testing:
    server:
      port: 8080
    database:
      name: forder_local
      host: localhost
      port: 5432
      user: forder_user
      password: forder_pass

  production:
    server:
      port: 8080
    database:
      name: forder_local
      host: localhost
      port: 5432
      user: forder_user
      password: forder_pass